/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CaseAnalysisInput = IDL.Record({
  'lawType' : IDL.Text,
  'documentContext' : IDL.Opt(IDL.Text),
  'caseDescription' : IDL.Text,
});
export const CaseAnalysisResult = IDL.Record({
  'caseType' : IDL.Text,
  'userRights' : IDL.Text,
  'oppositionArguments' : IDL.Vec(IDL.Text),
  'applicableLaw' : IDL.Text,
  'procedure' : IDL.Text,
});
export const FeedbackInput = IDL.Record({
  'lawType' : IDL.Text,
  'fullConversation' : IDL.Vec(IDL.Text),
});
export const FeedbackResponse = IDL.Record({
  'weaknesses' : IDL.Vec(IDL.Text),
  'suggestions' : IDL.Vec(IDL.Text),
  'strengths' : IDL.Vec(IDL.Text),
});
export const PracticeModeInput = IDL.Record({
  'lawType' : IDL.Text,
  'conversationHistory' : IDL.Vec(IDL.Text),
  'userInput' : IDL.Text,
});
export const PracticeModeResponse = IDL.Record({
  'counterArgument' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'analyzeCase' : IDL.Func([CaseAnalysisInput], [CaseAnalysisResult], []),
  'downloadDocument' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getFeedback' : IDL.Func([FeedbackInput], [FeedbackResponse], []),
  'practiceMode' : IDL.Func([PracticeModeInput], [PracticeModeResponse], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'uploadDocument' : IDL.Func([ExternalBlob, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CaseAnalysisInput = IDL.Record({
    'lawType' : IDL.Text,
    'documentContext' : IDL.Opt(IDL.Text),
    'caseDescription' : IDL.Text,
  });
  const CaseAnalysisResult = IDL.Record({
    'caseType' : IDL.Text,
    'userRights' : IDL.Text,
    'oppositionArguments' : IDL.Vec(IDL.Text),
    'applicableLaw' : IDL.Text,
    'procedure' : IDL.Text,
  });
  const FeedbackInput = IDL.Record({
    'lawType' : IDL.Text,
    'fullConversation' : IDL.Vec(IDL.Text),
  });
  const FeedbackResponse = IDL.Record({
    'weaknesses' : IDL.Vec(IDL.Text),
    'suggestions' : IDL.Vec(IDL.Text),
    'strengths' : IDL.Vec(IDL.Text),
  });
  const PracticeModeInput = IDL.Record({
    'lawType' : IDL.Text,
    'conversationHistory' : IDL.Vec(IDL.Text),
    'userInput' : IDL.Text,
  });
  const PracticeModeResponse = IDL.Record({ 'counterArgument' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'analyzeCase' : IDL.Func([CaseAnalysisInput], [CaseAnalysisResult], []),
    'downloadDocument' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getFeedback' : IDL.Func([FeedbackInput], [FeedbackResponse], []),
    'practiceMode' : IDL.Func([PracticeModeInput], [PracticeModeResponse], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'uploadDocument' : IDL.Func([ExternalBlob, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };