/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CaseAnalysisInput {
  'lawType' : string,
  'documentContext' : [] | [string],
  'caseDescription' : string,
}
export interface CaseAnalysisResult {
  'caseType' : string,
  'userRights' : string,
  'oppositionArguments' : Array<string>,
  'applicableLaw' : string,
  'procedure' : string,
}
export type ExternalBlob = Uint8Array;
export interface FeedbackInput {
  'lawType' : string,
  'fullConversation' : Array<string>,
}
export interface FeedbackResponse {
  'weaknesses' : Array<string>,
  'suggestions' : Array<string>,
  'strengths' : Array<string>,
}
export interface PracticeModeInput {
  'lawType' : string,
  'conversationHistory' : Array<string>,
  'userInput' : string,
}
export interface PracticeModeResponse { 'counterArgument' : string }
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'analyzeCase' : ActorMethod<[CaseAnalysisInput], CaseAnalysisResult>,
  'downloadDocument' : ActorMethod<[string], [] | [string]>,
  'getFeedback' : ActorMethod<[FeedbackInput], FeedbackResponse>,
  'practiceMode' : ActorMethod<[PracticeModeInput], PracticeModeResponse>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'uploadDocument' : ActorMethod<[ExternalBlob, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];